name: lark_msg_hot_server
server_id: 1
log: "./configs/logger.yaml"
etcd:
  endpoints: ["lark-etcd:12379"]
  username:
  password:
  schema: lark
  read_timeout: 5000
  write_timeout: 5000
  dial_timeout: 5000
mongo:
  address: "lark-mongo-msg:27017"
  username: admin
  password: lark2022
  db: lark
  direct: false
  timeout: 5000
  max_pool_size: 20
  retain_chat_records: 3650
redis:
  address: ["lark-redis:63791"]
  db: 0
  password: lark2022
  prefix: "LK:"
msg_consumer:
  address: ["lark-kafka:9092"]
  topic: ["to_inbox"]
  group_id: mongo