name: lark_msg_history_server
server_id: 1
log: "./configs/logger.yaml"
etcd:
  endpoints: ["lark-etcd:12379"]
  username:
  password:
  schema: lark
  read_timeout: 5000
  write_timeout: 5000
  dial_timeout: 5000
mysql:
  address: "lark-mysql-msg:13307"
  username: root
  password: lark2022
  db: lark_chat_msg
  max_open_conn: 20
  max_idle_conn: 10
  conn_lifetime: 120000
  charset: utf8
redis:
  address: ["lark-redis:63791"]
  db: 0
  password: lark2022
  prefix: "LK:"
msg_consumer:
  address: ["lark-kafka:9092"]
  topic: ["to_inbox"]
  group_id: mysql
